version: '2'
services:
  wasalnymicro-app:
    image: wasalnymicro
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://wasalnymicro-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=wasalnymicro
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
      - SPRING_DATA_JEST_URI=http://wasalnymicro-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://wasalnymicro-elasticsearch:9200
  wasalnymicro-mongodb:
    extends:
      file: mongodb.yml
      service: wasalnymicro-mongodb
  wasalnymicro-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: wasalnymicro-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
